spring:
  application:
    name: CHURNINSIGHT_ONE_BK_J17

  profiles:
    active: h2

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE



server:
    port: 8060
    error:
        include-stacktrace: never


