server:
  port: ${app.port}

spring:
  application:
    name: CHURNINSIGHT_ONE_BK_J17

  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

security:
  jwt:
    key:
      private: ${app.jwt.secret}
      public: ${app.jwt.public}
    user:
      generator: churninsight-api
    time:
      expiration: ${app.jwt.expiration}